export default {
  Stomach: '#a6cee3',
  Ovary: '#1f78b4',
  Bone: '#b2df8a',
  Breast: '#33a02c',
  'Central Nervous System': '#fb9a99',
  'Haematopoietic and Lymphoid': '#e31a1c',
  'Large Intestine': '#fdbf6f',
  Lung: '#ff7f00',
  Pancreas: '#cab2d6',
  'Peripheral Nervous System': '#6a3d9a',
  'Biliary Tract': '#ffff99',
  Endometrium: '#b15928',
  'Soft Tissue': '#fda4dd',
  Esophagus: '#fdea5f',
  'Head and Neck': '#668cfd',
  Skin: '#DDDDDD',
  Kidney: '#FE3000',
  Prostate: '#504ADF',
};
